### ISSUE TITLE
Backport versions

### ISSUE THREAD

**Issue by jurraca** [fjahr/rpki-client-nix#10]
This repo provides a bash script to help run a different version of rpki-client (see `versions.nix`). The upstream rpki-client repo updates pretty often and we're missing a few versions between 8.6 and 9.1.
For completeness, we should:
- add the missing version commit hashes for both [portable](https://github.com/rpki-client/rpki-client-portable/) and [openbsd](https://github.com/rpki-client/rpki-client-openbsd/) repos in `versions.nix` and
- test that they all build correctly.

**Comment by fjahr** [comment]
I am a bit confused, the description sounds like a PR but this is an issue. Did you open the wrong thing by accident or is this something you plan to do in the future with a separate PR?

**Comment by jurraca** [comment]
yea I meant this as an issue, reworded a bit.
